### ISSUE TITLE
壊せるブロックを作る

### ISSUE THREAD

**Issue by dugite-git** [CASru-GAME/BreakOut2024summer#8]
以下の要素を持ったプレハブを作成する

**Comment by Motoki4472** [comment]
-パラメータ
    -HP
    -ブロックが持つskillのリスト
-ブロックのHPを減らす関数（ブロックのHPが0ならブロックを破壊する）

**Comment by dugite-git** [comment]
- ブロックを破壊する変数

**Comment by dugite-git** [comment]
コライダーを持つ

**Comment by dugite-git** [comment]
- ブロック破壊の直前に行うべき操作をする関数

**Comment by dugite-git** [comment]
インターフェイスを使う
⇒ターゲットのブロックとそれ以外のブロックのクラスを分ける
⇒プレハブもわける
